# Generated by Django 5.0.14 on 2026-08-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('budget_category', models.CharField(choices=[('budget', 'Budget-friendly'), ('mid_range', 'Mid-range'), ('luxury', 'Luxury / High-end')], default='mid_range', max_length=20)),
                ('travel_style', models.CharField(choices=[('adventure', 'Adventure & Exploration'), ('relaxed', 'Relaxed & Leisurely'), ('cultural', 'Cultural & Historical'), ('foodie', 'Culinary & Foodie tour'), ('general', 'General Sightseeing')], default='general', max_length=20)),
                ('interests', models.TextField(blank=True, null=True)),
                ('itinerary_content', models.TextField()),
                ('budget_estimate', models.TextField(blank=True, null=True)),
                ('packing_list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
